### ISSUE TITLE
Startup failed PHP support for PostgreSQL is required

### ISSUE THREAD

**Issue by alphat5** [JC5/docker-ttrss#3]
Hi, I just freshly installed by making my own docker-compose.yml file. And after setting all de environment variables I get the following error on the web page. Do you maybe have an idea on how I can fix this?
![startup-failed](https://user-images.githubusercontent.com/11696836/75726063-f5d51180-5ce1-11ea-8099-c571468fe133.png)

` PHP support for PostgreSQL is required for configured DB_TYPE in config.php`

**Setup**
VPS 64 Bits (OVH SSD1) Running Debian 9
Nginx Reverse-Proxy is Dockerised

**docker-compose.yml**

```
version: '3'

services:
  app:
    image: jc5x/ttrss
    restart: unless-stopped
    environment:
      - DB_TYPE=pgsql
      - DB_PORT=5432
      - DB_HOST=172.29.0.4
      - DB_NAME=ttrss
      - DB_ENV_NAME=ttrss
      - DB_ENV_PASS=ttrss
      - DB_USER=ttrss
      - DB_PASS=_hidden_
      - OWNER_UID=1000
      - OWNER_GID=1000
      - SELF_URL_PATH=https://_hidden_
      - VIRTUAL_HOST=_hidden_
      - VIRTUAL_PORT=8280
      - LETSENCRYPT_HOST=_hidden_
      - VIRTUAL_NETWORK=nginx-proxy
      - SELF_URL=https://_hidden_
    volumes:
      - app:/var/www/html
    expose:
      - 8280
volumes:
  app: ~

networks:
   default:
      external:
        name: reverse
```

This seems to be a duplicated to #1 

Thanks in advance,
Cheers,
